---
- name: Test Playbook to Check Execution
  hosts: windows
  tasks:
    - name: Get Windows Version
      win_shell: |
        [System.Environment]::OSVersion.Version
      register: os_version

    - name: Show Windows Version
      debug:
        var: os_version.stdout

