---
- name: Test Ansible connectivity with Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check connectivity to Windows PC
      win_ping:

    - name: Create a test directory
      win_file:
        path: C:\ansible_test
        state: directory

    - name: Create a test file in the directory
      win_file:
        path: C:\ansible_test\test_file.txt
        state: touch

    - name: Write a test message to the file
      win_shell: echo "Ansible test successful!" > C:\ansible_test\test_file.txt
